### ISSUE TITLE
Not able to launch cacti in container

### ISSUE THREAD

**Issue by zgoda-mobica** [QuantumObject/docker-cacti#30]
OS X 10.13.6, docker 18.06.1-ce-mac73 relevant fragment of `docker-compose.yml` as copied from https://github.com/QuantumObject/docker-cacti/blob/master/docker-compose.yml:

```
  cacti:
    image: quantumobject/docker-cacti
    ports:
      - "80:80"
      - "161:161"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backups/:/var/backups/
    environment:
      - TZ=Europe/London
```

Started with

```
Mounts denied:
The path /etc/localtime
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info..
```

So I added `/etc/localtime` to shared paths. Then: 

```
ERROR: for cacti  Cannot start service cacti: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists
```

`/etc/localtime` is normally symlink to some file, so why `mkdir`?

```
$ ls -la /etc/localtime 
lrwxrwxrwx. 1 root root 35 Sep 25  2017 /etc/localtime -> ../usr/share/zoneinfo/Europe/London  # linux
lrwxr-xr-x  1 root  wheel  39 10 Sep 08:54 /etc/localtime -> /var/db/timezone/zoneinfo/Europe/London  # osx
```
